# -*- mode: python ; coding: utf-8 -*-
import os
import certifi
cert_file = certifi.where()

# Generated by scripts/generate_version_info.py from the release tag (see
# .github/workflows/release.yaml). Absent for local dev builds, in which
# case PyInstaller skips embedding version info.
version_file = "version_info.txt" if os.path.exists("version_info.txt") else None

a = Analysis(
    ['run.py'],
    pathex=[],
    binaries=[],
    datas=[('frontend', 'frontend'), ('portal/default_config.yaml', 'portal'), (cert_file, 'certifi'),
          ('assets', 'assets'), ('alembic', 'alembic'), ('alembic.ini', '.')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=2,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='GovCrawler',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/favicon.ico',
    version=version_file,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='GovCrawler',
)
